[

    {
        "error": false,
        "message": "Retrieve successfully.",
        "data": {
            "HotelSearchResult": {
                "ResponseStatus": 1,
                "Error": {
                    "ErrorCode": 0,
                    "ErrorMessage": ""
                },
                "TraceId": "4abd9caf-8223-4ea0-85b3-4bc1f13874ac",
                "CityId": "130443",
                "Remarks": "india - land of mystries \"//\" \"  /// \"  ",
                "CheckInDate": "2023-12-22",
                "CheckOutDate": "2023-12-23",
                "PreferredCurrency": "INR",
                "NoOfRooms": 2,
                "RoomGuests": [
                    {
                        "NoOfAdults": 1,
                        "NoOfChild": 0,
                        "ChildAge": []
                    },
                    {
                        "NoOfAdults": 1,
                        "NoOfChild": 0,
                        "ChildAge": []
                    }
                ],
                "HotelResults": [
                    {
                        "IsHotDeal": false,
                        "ResultIndex": 1,
                        "HotelCode": "13083538",
                        "HotelName": "Pride Plaza Hotel Aerocity New Delhi",
                        "HotelCategory": "",
                        "StarRating": 5,
                        "HotelDescription": "",
                        "HotelPromotion": "",
                        "HotelPolicy": "",
                        "Price": {
                            "CurrencyCode": "INR",
                            "RoomPrice": 9464.64,
                            "Tax": 0,
                            "ExtraGuestCharge": 0,
                            "ChildCharge": 0,
                            "OtherCharges": 5614.62,
                            "Discount": 0,
                            "PublishedPrice": 25986.87,
                            "PublishedPriceRoundedOff": 25987,
                            "OfferedPrice": 15079.26,
                            "OfferedPriceRoundedOff": 15079,
                            "AgentCommission": 10907.61,
                            "AgentMarkUp": 4331.28,
                            "ServiceTax": 1010.95,
                            "TCS": 0,
                            "TDS": 0,
                            "ServiceCharge": 0,
                            "TotalGSTAmount": 1010.9491,
                            "GST": {
                                "CGSTAmount": 0,
                                "CGSTRate": 0,
                                "CessAmount": 0,
                                "CessRate": 0,
                                "IGSTAmount": 1010.9491,
                                "IGSTRate": 18,
                                "SGSTAmount": 0,
                                "SGSTRate": 0,
                                "TaxableAmount": 5614.62
                            }
                        },
                        "HotelPicture": "https://b2b.tektravels.com/Images/HotelNA.jpg",
                        "HotelAddress": "5-A, Hospitality District, Aerocity,Indra Gandhi International Airport,New Delhi,Delhi,IN, , , , ",
                        "HotelContactNo": "",
                        "HotelMap": null,
                        "Latitude": "",
                        "Longitude": "",
                        "HotelLocation": null,
                        "SupplierPrice": null,
                        "RoomDetails": []
                    },
                    {
                        "IsHotDeal": false,
                        "ResultIndex": 2,
                        "HotelCode": "16343409",
                        "HotelName": "Airport Hotel Grand Delhi",
                        "HotelCategory": "",
                        "StarRating": 4,
                        "HotelDescription": "",
                        "HotelPromotion": "",
                        "HotelPolicy": "",
                        "Price": {
                            "CurrencyCode": "INR",
                            "RoomPrice": 10971.14,
                            "Tax": 0,
                            "ExtraGuestCharge": 0,
                            "ChildCharge": 0,
                            "OtherCharges": 6508.83,
                            "Discount": 0,
                            "PublishedPrice": 30125.17,
                            "PublishedPriceRoundedOff": 30125,
                            "OfferedPrice": 17479.97,
                            "OfferedPriceRoundedOff": 17480,
                            "AgentCommission": 12645.2,
                            "AgentMarkUp": 5020.6,
                            "ServiceTax": 1171.37,
                            "TCS": 0,
                            "TDS": 0,
                            "ServiceCharge": 0,
                            "TotalGSTAmount": 1171.3668,
                            "GST": {
                                "CGSTAmount": 0,
                                "CGSTRate": 0,
                                "CessAmount": 0,
                                "CessRate": 0,
                                "IGSTAmount": 1171.3668,
                                "IGSTRate": 18,
                                "SGSTAmount": 0,
                                "SGSTRate": 0,
                                "TaxableAmount": 6508.83
                            }
                        },
                        "HotelPicture": "https://b2b.tektravels.com/Images/HotelNA.jpg",
                        "HotelAddress": "L-73 L-Block, Mahipalpur Extention, NH8,Near IGI Airport, Mahipalpur,New Delhi,Delhi,IN, , , , ",
                        "HotelContactNo": "",
                        "HotelMap": null,
                        "Latitude": "",
                        "Longitude": "",
                        "HotelLocation": null,
                        "SupplierPrice": null,
                        "RoomDetails": []
                    },
                    {
                        "IsHotDeal": false,
                        "ResultIndex": 7,
                        "HotelCode": "11960",
                        "HotelName": "Test Property",
                        "HotelCategory": "",
                        "StarRating": 5,
                        "HotelDescription": "Test Description  ",
                        "HotelPromotion": "",
                        "HotelPolicy": "",
                        "Price": {
                            "CurrencyCode": "INR",
                            "RoomPrice": 19186.59,
                            "Tax": 0,
                            "ExtraGuestCharge": 0,
                            "ChildCharge": 0,
                            "OtherCharges": 635.32,
                            "Discount": 0,
                            "PublishedPrice": 19821.91,
                            "PublishedPriceRoundedOff": 19822,
                            "OfferedPrice": 19821.91,
                            "OfferedPriceRoundedOff": 19822,
                            "AgentCommission": 0,
                            "AgentMarkUp": 3303.65,
                            "ServiceTax": 114.36,
                            "TCS": 0,
                            "TDS": 0,
                            "ServiceCharge": 0,
                            "TotalGSTAmount": 114.3572,
                            "GST": {
                                "CGSTAmount": 0,
                                "CGSTRate": 0,
                                "CessAmount": 0,
                                "CessRate": 0,
                                "IGSTAmount": 114.3572,
                                "IGSTRate": 18,
                                "SGSTAmount": 0,
                                "SGSTRate": 0,
                                "TaxableAmount": 635.32
                            }
                        },
                        "HotelPicture": "ENGeeb57131-4453-4eac-a5d9-74eccdc95dce.jpg",
                        "HotelAddress": "city center, city center, Delhi, 211222",
                        "HotelContactNo": "",
                        "HotelMap": null,
                        "Latitude": "0",
                        "Longitude": "0",
                        "HotelLocation": null,
                        "SupplierPrice": null,
                        "RoomDetails": []
                    },
                    {
                        "IsHotDeal": false,
                        "ResultIndex": 4,
                        "HotelCode": "13083538",
                        "HotelName": "Pride Plaza Hotel Aerocity New Delhi",
                        "HotelCategory": "",
                        "StarRating": 5,
                        "HotelDescription": "",
                        "HotelPromotion": "",
                        "HotelPolicy": "",
                        "Price": {
                            "CurrencyCode": "INR",
                            "RoomPrice": 16682.65,
                            "Tax": 0,
                            "ExtraGuestCharge": 0,
                            "ChildCharge": 0,
                            "OtherCharges": 5614.62,
                            "Discount": 0,
                            "PublishedPrice": 25986.87,
                            "PublishedPriceRoundedOff": 25987,
                            "OfferedPrice": 22297.27,
                            "OfferedPriceRoundedOff": 22297,
                            "AgentCommission": 3689.61,
                            "AgentMarkUp": 4331.28,
                            "ServiceTax": 1010.95,
                            "TCS": 0,
                            "TDS": 0,
                            "ServiceCharge": 0,
                            "TotalGSTAmount": 1010.9491,
                            "GST": {
                                "CGSTAmount": 0,
                                "CGSTRate": 0,
                                "CessAmount": 0,
                                "CessRate": 0,
                                "IGSTAmount": 1010.9491,
                                "IGSTRate": 18,
                                "SGSTAmount": 0,
                                "SGSTRate": 0,
                                "TaxableAmount": 5614.62
                            }
                        },
                        "HotelPicture": "https://b2b.tektravels.com/Images/HotelNA.jpg",
                        "HotelAddress": "5-A, Hospitality District, Aerocity,Indra Gandhi International Airport,New Delhi,Delhi,IN, , , , ",
                        "HotelContactNo": "",
                        "HotelMap": null,
                        "Latitude": "",
                        "Longitude": "",
                        "HotelLocation": null,
                        "SupplierPrice": null,
                        "RoomDetails": []
                    },
                    {
                        "IsHotDeal": false,
                        "ResultIndex": 5,
                        "HotelCode": "16343409",
                        "HotelName": "Airport Hotel Grand Delhi",
                        "HotelCategory": "",
                        "StarRating": 4,
                        "HotelDescription": "",
                        "HotelPromotion": "",
                        "HotelPolicy": "",
                        "Price": {
                            "CurrencyCode": "INR",
                            "RoomPrice": 19339.07,
                            "Tax": 0,
                            "ExtraGuestCharge": 0,
                            "ChildCharge": 0,
                            "OtherCharges": 6508.83,
                            "Discount": 0,
                            "PublishedPrice": 30125.17,
                            "PublishedPriceRoundedOff": 30125,
                            "OfferedPrice": 25847.9,
                            "OfferedPriceRoundedOff": 25848,
                            "AgentCommission": 4277.28,
                            "AgentMarkUp": 5020.6,
                            "ServiceTax": 1171.37,
                            "TCS": 0,
                            "TDS": 0,
                            "ServiceCharge": 0,
                            "TotalGSTAmount": 1171.3668,
                            "GST": {
                                "CGSTAmount": 0,
                                "CGSTRate": 0,
                                "CessAmount": 0,
                                "CessRate": 0,
                                "IGSTAmount": 1171.3668,
                                "IGSTRate": 18,
                                "SGSTAmount": 0,
                                "SGSTRate": 0,
                                "TaxableAmount": 6508.83
                            }
                        },
                        "HotelPicture": "https://b2b.tektravels.com/Images/HotelNA.jpg",
                        "HotelAddress": "L-73 L-Block, Mahipalpur Extention, NH8,Near IGI Airport, Mahipalpur,New Delhi,Delhi,IN, , , , ",
                        "HotelContactNo": "",
                        "HotelMap": null,
                        "Latitude": "",
                        "Longitude": "",
                        "HotelLocation": null,
                        "SupplierPrice": null,
                        "RoomDetails": []
                    },
                    {
                        "IsHotDeal": false,
                        "ResultIndex": 3,
                        "HotelCode": "20160759",
                        "HotelName": "The Oberoi, New Delhi",
                        "HotelCategory": "",
                        "StarRating": 5,
                        "HotelDescription": "",
                        "HotelPromotion": "",
                        "HotelPolicy": "",
                        "Price": {
                            "CurrencyCode": "INR",
                            "RoomPrice": 29322.29,
                            "Tax": 0,
                            "ExtraGuestCharge": 0,
                            "ChildCharge": 0,
                            "OtherCharges": 17394.2,
                            "Discount": 0,
                            "PublishedPrice": 80511.42,
                            "PublishedPriceRoundedOff": 80511,
                            "OfferedPrice": 46716.49,
                            "OfferedPriceRoundedOff": 46716,
                            "AgentCommission": 33794.93,
                            "AgentMarkUp": 13418.7,
                            "ServiceTax": 3131.32,
                            "TCS": 0,
                            "TDS": 0,
                            "ServiceCharge": 0,
                            "TotalGSTAmount": 3131.3216,
                            "GST": {
                                "CGSTAmount": 0,
                                "CGSTRate": 0,
                                "CessAmount": 0,
                                "CessRate": 0,
                                "IGSTAmount": 3131.3216,
                                "IGSTRate": 18,
                                "SGSTAmount": 0,
                                "SGSTRate": 0,
                                "TaxableAmount": 17394.2
                            }
                        },
                        "HotelPicture": "https://b2b.tektravels.com/Images/HotelNA.jpg",
                        "HotelAddress": "Dr. Zakir Hussain Marg,New Delhi,Delhi,IN, , , , ",
                        "HotelContactNo": "",
                        "HotelMap": null,
                        "Latitude": "",
                        "Longitude": "",
                        "HotelLocation": null,
                        "SupplierPrice": null,
                        "RoomDetails": []
                    },
                    {
                        "IsHotDeal": false,
                        "ResultIndex": 6,
                        "HotelCode": "20160759",
                        "HotelName": "The Oberoi, New Delhi",
                        "HotelCategory": "",
                        "StarRating": 5,
                        "HotelDescription": "",
                        "HotelPromotion": "",
                        "HotelPolicy": "",
                        "Price": {
                            "CurrencyCode": "INR",
                            "RoomPrice": 51686.26,
                            "Tax": 0,
                            "ExtraGuestCharge": 0,
                            "ChildCharge": 0,
                            "OtherCharges": 17394.2,
                            "Discount": 0,
                            "PublishedPrice": 80511.42,
                            "PublishedPriceRoundedOff": 80511,
                            "OfferedPrice": 69080.47,
                            "OfferedPriceRoundedOff": 69080,
                            "AgentCommission": 11430.95,
                            "AgentMarkUp": 13418.7,
                            "ServiceTax": 3131.32,
                            "TCS": 0,
                            "TDS": 0,
                            "ServiceCharge": 0,
                            "TotalGSTAmount": 3131.3216,
                            "GST": {
                                "CGSTAmount": 0,
                                "CGSTRate": 0,
                                "CessAmount": 0,
                                "CessRate": 0,
                                "IGSTAmount": 3131.3216,
                                "IGSTRate": 18,
                                "SGSTAmount": 0,
                                "SGSTRate": 0,
                                "TaxableAmount": 17394.2
                            }
                        },
                        "HotelPicture": "https://b2b.tektravels.com/Images/HotelNA.jpg",
                        "HotelAddress": "Dr. Zakir Hussain Marg,New Delhi,Delhi,IN, , , , ",
                        "HotelContactNo": "",
                        "HotelMap": null,
                        "Latitude": "",
                        "Longitude": "",
                        "HotelLocation": null,
                        "SupplierPrice": null,
                        "RoomDetails": []
                    }
                ]
            }
        }
    }
]