export const image = {
    upiIcon : require("../assets/service-icon/RechargeAndBillPayment/upi.png"),
    contact : require("../assets/service-icon/RechargeAndBillPayment/contact.png"),
    mobile : require("../assets/service-icon/RechargeAndBillPayment/mobile.png"),
    gas : require("../assets/service-icon/RechargeAndBillPayment/gas.png"),
    electicbill : require("../assets/service-icon/RechargeAndBillPayment/electic.png"),
    water : require("../assets/service-icon/RechargeAndBillPayment/water.png"),
    upivia : require("../assets/service-icon/RechargeAndBillPayment/upi-via.png"),
    dth : require("../assets/service-icon/RechargeAndBillPayment/dth.png"),
    boardband : require("../assets/service-icon/RechargeAndBillPayment/boardband.png"),
    municipal : require("../assets/service-icon/RechargeAndBillPayment/municipal.png"),
    credit : require("../assets/service-icon/RechargeAndBillPayment/credit-card.png"),
    health : require("../assets/service-icon/RechargeAndBillPayment/health.png"),
    fastag : require("../assets/service-icon/RechargeAndBillPayment/fastag_01.png"),
    wallet : require("../assets/service-icon/RechargeAndBillPayment/wallet.png"),
    Landline : require("../assets/service-icon/RechargeAndBillPayment/landline_01.png"),
    insurance_01 : require("../assets/service-icon/RechargeAndBillPayment/insurance_01.png"),
    loan : require("../assets/service-icon/RechargeAndBillPayment/abc.png"),

    // Banking Services & Insurance Services images
    AEPS : require("../assets/service-icon/bankingServices/AEPS.png"),
    MoneyTransfer : require("../assets/service-icon/bankingServices/Money Transfer.png"),
    CashDeposit : require("../assets/service-icon/bankingServices/Cash Deposit.png"),
    Withdrawal : require("../assets/service-icon/bankingServices/Withdrawal.png"),
    PersonalLoan : require("../assets/service-icon/bankingServices/Parsonal Loan.png"),
    TravelInsurance : require("../assets/service-icon/bankingServices/Travel Insurance.png"),
    GroupTeamInsurance : require("../assets/service-icon/bankingServices/Group Team Insurance.png"),
    LifeInsurance : require("../assets/service-icon/bankingServices/Life Insurance.png"),
    CommercialInsurance : require("../assets/service-icon/bankingServices/Commercial Insurance.png"),
    BikeInsurance : require("../assets/service-icon/bankingServices/Bike Insurance.png"),
    CarInsurance : require("../assets/service-icon/bankingServices/Car Insurance.png"),

    // Tour & Travel Servicesimages
    Hotel : require("../assets/service-icon/TourTravel/Hotel.png"),
    Flights : require("../assets/service-icon/TourTravel/Flights.png"),
    Bus : require("../assets/service-icon/TourTravel/Bus.png"),
    Train : require("../assets/service-icon/TourTravel/Train.png"),
    TourTravel : require("../assets/service-icon/TourTravel/Tour Travel.png"),
    OffersPackage : require("../assets/service-icon/TourTravel/Offers Package.png"),

    // Financial Services Servicesimages
    CompanyFormation : require("../assets/service-icon/FinancialServices/Company Formation.png"),
    GST : require("../assets/service-icon/FinancialServices/GST.png"),
    PanCard : require("../assets/service-icon/FinancialServices/Pan Card.png"),
    ITR : require("../assets/service-icon/FinancialServices/ITR.png"),
    DesignDevelopment : require("../assets/service-icon/FinancialServices/Design Development.png"),
    AccountingServices : require("../assets/service-icon/FinancialServices/Accounting Services.png"),
    GoldInvestment : require("../assets/service-icon/FinancialServices/Gold Investment.png"),
    DigitalMarketing : require("../assets/service-icon/FinancialServices/Digital Marketing.png"),
    MutualFund : require("../assets/service-icon/FinancialServices/Mutual Fund.png"),
    BondInvestment : require("../assets/service-icon/FinancialServices/Bond Investment.png"),
    EducationFee : require("../assets/service-icon/FinancialServices/Education Fee.png"),
    DigitalSignature : require("../assets/service-icon/FinancialServices/Digital Signature.png"),
}